### ISSUE TITLE
On CA generation O (organization field) is hardcoded to "certify"

### ISSUE THREAD

**Issue by CompuRoot** [nothinux/certify#4]
## Test case:        

Create
```
caertify -init cn:CA-Universe expiry:3650d
```

read:          
```
caertify -read ca-cert.pem
```
Result:       
```
Issuer: CN=CA-Universe, O=certify
```    
Suggestion to add `O` (organization) SSL field or at least duplicate `CN` to `O`

**Comment by nothinux** [comment]
Yes, for now the `organization` was hardcoded to `certify` will add this to the backlog.
thanks for the suggestion

**Comment by nothinux** [comment]
Hi @CompuRoot now you can set the organization in the new version 1.6.0
